### PR TITLE
HTML return patching, 6 domain part support, sepolia ENS

### PR DESCRIPTION
**Pull request by nand2**
Hi!

This adds:
- Processing of the return of content-type HTML : 
  - patching the fetch() JS function so that it works with web3:// URLs
  - Handling <a> links to absolute web3:// URLs
  - -> This is not 100% perfect, will fail if the content is compressed and spread over several chunks (should be rare)
- Add support for 6 parts domains, so that ENS subdomains in testnet works, e.g. `dblog.dblog.eth.11155111.w3link.io`
- Add sample ENS config for sepolia in config.toml.sample

Thanks!

### CODE REVIEW

**Comment by syntrust** [comment]
Hi @nand2, it seems like an interesting feature, can you describe a little about the background and motivation?

**Comment by nand2** [comment]
Hi!

Sure! It's about contracts interacting with other contracts.

When a smart contract website A only interact with itself with javascript `fetch()` and <A> tags, we can make it work both on native web3:// browsers and on the gateway by using relative URLs (e.g. `fetch("/path/to/resource")` `<a href="/path">`.

But when a smart contract A wants to interact with smart contract B, then it has to use absolute URLs : `fetch("web3://contractB/path/to/resource")` `<a href="web3://contractB/path">`, and while this work on native web3:// browsers, it break on the gateway.

Until now, for small contracts, when we reached this issue, we kind of managed by modifying the architecture of the website, but as websites go bigger, it has to be the other way around.

The proposed patch is injecting javascript that look for these absolute web3:// URLs and replace them by their gateway HTTP URLs.

Thanks!

**Review by syntrust — APPROVED** [review]

**Review by qzhodl — APPROVED** [review]

**Comment by syntrust** [comment]
The PR merged and deployed to w3link.io.
Also added new A record `*.dblog.eth.11155111.w3link.io` and updated certificate.

When accessing https://dblog.eth.11155111.w3link.io/ I got

500: Internal Server Error
internal server error: 429 Too Many Requests: {"jsonrpc":"2.0","id":2,"error":{"code":-32005,"message":"project ID request rate exceeded","data":{"see":"https://infura.io/dashboard"}}}

we may need to check the infura rpc service

**Comment by qzhodl** [comment]
Do you also deploy the ENS support in the config file?

**Comment by qzhodl** [comment]
Do you also deploy the ENS support in the config file?

**Comment by nand2** [comment]
For this, you need : 
```
[name2chain]
"w3q-t" = 3333
```
in the config.
And it should be all good!

**Comment by nand2** [comment]
Ok saw the short name change from w3q-t to es-t, will deploy a version using this new short name for chain 3333.

**Comment by syntrust** [comment]
```
[name2chain]
"es-t" = 3333
```

This one works, would you like to make the change in this PR? @nand2

**Pull request merged**
